language: ruby
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
- bundle install
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails test
- bundle exec rails test:system
