language: ruby
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "addisonmartin-github"
    token: ${SONAR_TOKEN}
script:
- bundle install
- bundle exec rails db:create
- bundle exec rails db:migrate
- sonar-scanner
- bundle exec rubocop --require rubocop-performance && bundle exec rails test && bundle exec rails test:system
